name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.0
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
